// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCc_hFABbqQuLXP1KWHZU3nLQNe3PJ1_Mw',
    appId: '1:111460836207:web:5bb6c8f2e4bdba8ba63e9a',
    messagingSenderId: '111460836207',
    projectId: 'thatsnot-71ba4',
    authDomain: 'thatsnot-71ba4.firebaseapp.com',
    storageBucket: 'thatsnot-71ba4.appspot.com',
    measurementId: 'G-DYHTP88J6G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7akbG58HVApadTDa4ECkq3qJbEO7Zldg',
    appId: '1:111460836207:android:cc2423442fde589ba63e9a',
    messagingSenderId: '111460836207',
    projectId: 'thatsnot-71ba4',
    storageBucket: 'thatsnot-71ba4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBl74JD3ShPk8lkXHB358qvkfyQUzyVSkQ',
    appId: '1:111460836207:ios:a99a65d64c8b5ef9a63e9a',
    messagingSenderId: '111460836207',
    projectId: 'thatsnot-71ba4',
    storageBucket: 'thatsnot-71ba4.appspot.com',
    iosBundleId: 'com.example.thatsnot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBl74JD3ShPk8lkXHB358qvkfyQUzyVSkQ',
    appId: '1:111460836207:ios:219cbc37f10d19bea63e9a',
    messagingSenderId: '111460836207',
    projectId: 'thatsnot-71ba4',
    storageBucket: 'thatsnot-71ba4.appspot.com',
    iosBundleId: 'com.example.thatsnot.RunnerTests',
  );
}
